export default {
  allAgents: [
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'John K',
      confirmed: true,
      email: 'john@sarv.com',
      id: 1,
      name: 'John Kennady',
      role: 'administrator',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Samuel K',
      confirmed: true,
      email: 'samuel@sarv.com',
      id: 2,
      name: 'Samuel Keta',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'offline',
      available_name: 'James K',
      confirmed: true,
      email: 'james@sarv.com',
      id: 3,
      name: 'James Koti',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Honey',
      confirmed: true,
      email: 'bee@sarv.com',
      id: 4,
      name: 'Honey Bee',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'Abraham',
      confirmed: true,
      email: 'abraham@sarv.com',
      id: 5,
      name: 'Abraham Keta',
      role: 'agent',
    },
  ],
  formattedAgents: [
    {
      account_id: 0,
      confirmed: true,
      email: 'None',
      id: 0,
      name: 'None',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'Abraham',
      confirmed: true,
      email: 'abraham@sarv.com',
      id: 5,
      name: 'Abraham Keta',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'John K',
      confirmed: true,
      email: 'john@sarv.com',
      id: 1,
      name: 'John Kennady',
      role: 'administrator',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Honey',
      confirmed: true,
      email: 'bee@sarv.com',
      id: 4,
      name: 'Honey Bee',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Samuel K',
      confirmed: true,
      email: 'samuel@sarv.com',
      id: 2,
      name: 'Samuel Keta',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'offline',
      available_name: 'James K',
      confirmed: true,
      email: 'james@sarv.com',
      id: 3,
      name: 'James Koti',
      role: 'agent',
    },
  ],
  onlineAgents: [
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'Abraham',
      confirmed: true,
      email: 'abraham@sarv.com',
      id: 5,
      name: 'Abraham Keta',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'John K',
      confirmed: true,
      email: 'john@sarv.com',
      id: 1,
      name: 'John Kennady',
      role: 'administrator',
    },
  ],
  busyAgents: [
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Honey',
      confirmed: true,
      email: 'bee@sarv.com',
      id: 4,
      name: 'Honey Bee',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Samuel K',
      confirmed: true,
      email: 'samuel@sarv.com',
      id: 2,
      name: 'Samuel Keta',
      role: 'agent',
    },
  ],
  offlineAgents: [
    {
      account_id: 1,
      availability_status: 'offline',
      available_name: 'James K',
      confirmed: true,
      email: 'james@sarv.com',
      id: 3,
      name: 'James Koti',
      role: 'agent',
    },
  ],
  sortedByAvailability: [
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'Abraham',
      confirmed: true,
      email: 'abraham@sarv.com',
      id: 5,
      name: 'Abraham Keta',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'John K',
      confirmed: true,
      email: 'john@sarv.com',
      id: 1,
      name: 'John Kennady',
      role: 'administrator',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Honey',
      confirmed: true,
      email: 'bee@sarv.com',
      id: 4,
      name: 'Honey Bee',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'busy',
      available_name: 'Samuel K',
      confirmed: true,
      email: 'samuel@sarv.com',
      id: 2,
      name: 'Samuel Keta',
      role: 'agent',
    },
    {
      account_id: 1,
      availability_status: 'offline',
      available_name: 'James K',
      confirmed: true,
      email: 'james@sarv.com',
      id: 3,
      name: 'James Koti',
      role: 'agent',
    },
  ],
  formattedAgentsByPresenceOnline: [
    {
      account_id: 1,
      availability_status: 'online',
      available_name: 'Abraham',
      confirmed: true,
      email: 'abr@sarv.com',
      id: 1,
      name: 'Abraham Keta',
      role: 'agent',
    },
  ],
  formattedAgentsByPresenceOffline: [
    {
      account_id: 1,
      availability_status: 'offline',
      available_name: 'Abraham',
      confirmed: true,
      email: 'abr@sarv.com',
      id: 1,
      name: 'Abraham Keta',
      role: 'agent',
    },
  ],
};
